### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by SenrirenTokyo** [lmcintyre/ZoneFbx#1]
Not sure what to do. Following the video gets me "Unhandled Exception" after processing BGs. I can export textures but not the models for some reason. :( 
Using latest version of Zone Fbx and Godbert.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Lumina.Models.Models.Model..ctor(GameData data, String path, ModelLod lod, Int32 variantId) in C:\Users\Liam\Documents\repos\Lumina\src\Lumina\Models\Models\Model.cs:line 74
   at ZoneExporter.process_bg(ZoneExporter* ) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneExporter.cpp:line 115
   at ZoneExporter.export_zone(ZoneExporter* , String A_0, String A_1, String A_2) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneExporter.cpp:line 37
   at main(String[] args) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneFbx.cpp:line 63
   at mainCRTStartupStrArray(String[] arguments) in d:\A01\_work\12\s\src\vctools\crt\crtw32\msilcrt\mcrtexe.cpp:line 247

**Comment by SenrirenTokyo** [comment]
To be more clear on where it fails:

Initializing...
Processing models and textures...
Processing zone terrain.
Processing bg.lgb...

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Lumina.Models.Models.Model..ctor(GameData data, String path, ModelLod lod, Int32 variantId) in C:\Users\Liam\Documents\repos\Lumina\src\Lumina\Models\Models\Model.cs:line 74
   at ZoneExporter.process_bg(ZoneExporter* ) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneExporter.cpp:line 115
   at ZoneExporter.export_zone(ZoneExporter* , String A_0, String A_1, String A_2) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneExporter.cpp:line 37
   at main(String[] args) in C:\Users\Liam\Documents\repos\ZoneFbx\ZoneFbx\ZoneFbx.cpp:line 63
   at mainCRTStartupStrArray(String[] arguments) in d:\A01\_work\12\s\src\vctools\crt\crtw32\msilcrt\mcrtexe.cpp:line 247
PS C:\Users\Snowwi\Desktop\Godbert\fbx>

**Comment by lmcintyre** [comment]
Hi, sorry about this error. I am currently doing some behind the scenes work on some Lumina things (the library that ZoneFbx uses) in order to provide better capabilities to ZoneFbx. In the process, I'll be using ZoneFbx to test those changes and hopefully I'll have the ability to improve the reliability of ZoneFbx as a whole, but it will probably be some time until this is fixed.
